CHROMA_PATH = "./data/chroma"
CHROMA_COLLECTION = "bubblehead"

OLLAMA_BASE_URL = "http://localhost:11434"
EMBED_MODEL = "mistral:7b"
LLM_MODEL = "mistral:7b"
LLM_TEMPERATURE = 0.3

CHUNK_SIZE = 512
CHUNK_OVERLAP = 50

TOP_K_CANDIDATES = 10
TOP_K_FINAL = 6
TOKEN_BUDGET = 5000

GAP_CONFIDENCE_THRESHOLD = 0.72
GAP_MAX_ITERATIONS = 4
